### ISSUE TITLE
nuxt.config.ts type issue

### ISSUE THREAD

**Issue by ejerskov** [NasonTech/nuxt-update-available#1]
When adding `checkOutdatedBuildInterval` to nuxt.config.ts experimental settings, I get this error in my IDE:

![image](https://github.com/user-attachments/assets/d0c04d09-9059-4a3b-be00-c71dce290281)

My project is building without errors but the `updateAvailable` is never triggered on new deploy, so it doesnt seem to work.
Im running a nuxt 3 project deployed to vercel

**Comment by bnason** [comment]
What version of Nuxt are you on? I believe this feature was release in v3.12.0

**Comment by ejerskov** [comment]
Thanks for clearing that up - Im running v.3.11.2

Maybe consider adding this min. version to the documentation

**Comment by bnason** [comment]
Done! [Minimum Requirements](https://github.com/NasonTech/nuxt-update-available?tab=readme-ov-file#minimum-requirements)
